name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TF_ROOT: "./gha-image/"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin
        docker image build -t dab8106/pyflask:latest .
        docker push dab8106/pyflask:latest
      working-directory: "${{ env.TF_ROOT }}"